"""Generate Markdown and HTML pentest reports from workspace + loot + findings."""
from __future__ import annotations

import html as _html
from datetime import datetime
from spectrenet.workspace import Workspace
from spectrenet.loot import LootVault


def generate_report(
    workspace: Workspace,
    loot: LootVault,
    hosts: dict,
    operator: str = "operator",
) -> str:
    now   = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []

    lines += [
        "# SpectreNet Pentest Report",
        "",
        f"**Operator:** {operator}  ",
        f"**Generated:** {now}  ",
        f"**Targets:** {', '.join(workspace.targets) if workspace.targets else 'N/A'}",
        "",
        "---",
        "",
    ]

    # ── Scope / Targets ───────────────────────────────────────────────────
    if workspace.targets:
        lines += ["## Targets", ""]
        for t in workspace.targets:
            lines.append(f"- `{t}`")
        lines.append("")

    # ── Findings (from Findings Panel) ───────────────────────────────────
    if hosts:
        lines += ["## Network Findings", ""]
        for ip, ports in sorted(hosts.items()):
            lines.append(f"### {ip}")
            lines.append("")
            lines.append("| Port | Proto | Service | Version |")
            lines.append("|------|-------|---------|---------|")
            for p in sorted(ports, key=lambda x: int(x.get("port", 0) or 0)):
                port    = p.get("port",    "")
                proto   = p.get("proto",   "tcp")
                service = p.get("service", "")
                version = p.get("version", "")
                lines.append(f"| {port} | {proto} | {service} | {version} |")
            lines.append("")

    # ── Loot / Credentials ───────────────────────────────────────────────
    all_loot = loot.all()
    if all_loot:
        lines += ["## Loot & Credentials", ""]
        for loot_type in LootVault.TYPES:
            entries = loot.by_type(loot_type)
            if not entries:
                continue
            lines.append(f"### {loot_type.capitalize()}s")
            lines.append("")
            for e in entries:
                ts = e["t"][:16]
                lines.append(f"- `{e['text']}`  _{ts}_")
            lines.append("")

    # ── Notes ─────────────────────────────────────────────────────────────
    if workspace.notes:
        lines += ["## Notes", ""]
        for n in workspace.notes:
            ts = n["t"][:16]
            lines.append(f"- {n['text']}  _{ts}_")
        lines.append("")

    # ── Findings from workspace ───────────────────────────────────────────
    if workspace.findings:
        lines += ["## Findings (Workspace)", ""]
        for f in workspace.findings:
            lines.append(f"- {f}")
        lines.append("")

    # ── Command Timeline ──────────────────────────────────────────────────
    if workspace.commands:
        lines += ["## Command Timeline", "", "```"]
        for c in workspace.commands:
            ts = c["t"][:16]
            lines.append(f"[{ts}] {c['cmd']}")
        lines += ["```", ""]

    lines += [
        "---",
        "",
        "_Generated by SpectreNet — Always one step ahead_",
    ]

    return "\n".join(lines)


def generate_report_html(
    workspace: Workspace,
    loot: LootVault,
    hosts: dict,
    operator: str = "operator",
) -> str:
    """Generate a self-contained dark-themed HTML pentest report."""
    now   = datetime.now().strftime("%Y-%m-%d %H:%M")
    e     = _html.escape
    lines = []

    def h(text: str) -> str:
        return e(str(text))

    _CSS = """
    :root{--navy:#0d1117;--navy-l:#161b22;--cyan:#00d4ff;--cyan-d:#006080;
          --grey:#8b949e;--white:#e6edf3;--green:#3fb950;--yellow:#d29922;--red:#f85149}
    *{box-sizing:border-box;margin:0;padding:0}
    body{background:var(--navy);color:var(--white);
         font-family:'Cascadia Code','Fira Code',Consolas,monospace;font-size:13px;
         padding:32px;line-height:1.6}
    h1{color:var(--cyan);font-size:22px;letter-spacing:1px;margin-bottom:4px}
    h2{color:var(--cyan);font-size:14px;letter-spacing:1.5px;text-transform:uppercase;
       margin:28px 0 10px;padding-bottom:6px;border-bottom:1px solid var(--cyan-d)}
    h3{color:var(--white);font-size:13px;margin:16px 0 8px}
    .meta{color:var(--grey);font-size:11px;margin-bottom:24px}
    .meta span{margin-right:24px}
    table{width:100%;border-collapse:collapse;margin-bottom:16px}
    th{background:var(--navy-l);color:var(--cyan);padding:6px 10px;
       text-align:left;font-size:11px;letter-spacing:1px;text-transform:uppercase}
    td{padding:6px 10px;border-bottom:1px solid rgba(255,255,255,.05);
       color:var(--white);font-size:12px}
    tr:last-child td{border-bottom:none}
    .badge{display:inline-block;padding:2px 7px;border-radius:3px;font-size:10px;
           font-weight:bold;margin-right:4px}
    .badge-red   {background:rgba(248,81,73,.15);color:var(--red);border:1px solid var(--red)}
    .badge-yellow{background:rgba(210,153,34,.15);color:var(--yellow);border:1px solid var(--yellow)}
    .badge-cyan  {background:rgba(0,212,255,.10);color:var(--cyan);border:1px solid var(--cyan-d)}
    code{background:var(--navy-l);padding:1px 5px;border-radius:3px;color:var(--cyan);font-size:12px}
    pre{background:var(--navy-l);border:1px solid var(--cyan-d);border-radius:4px;
        padding:12px;overflow-x:auto;font-size:12px;color:var(--white)}
    ul{padding-left:20px}
    li{margin-bottom:4px}
    .note-item{color:var(--grey);font-size:12px;margin-bottom:4px}
    footer{margin-top:40px;color:var(--grey);font-size:11px;
           border-top:1px solid var(--cyan-d);padding-top:16px;text-align:center}
    """

    lines.append(f"<!DOCTYPE html><html lang='en'><head>")
    lines.append(f"<meta charset='UTF-8'/>")
    lines.append(f"<meta name='viewport' content='width=device-width,initial-scale=1'/>")
    lines.append(f"<title>SpectreNet Report — {h(now)}</title>")
    lines.append(f"<style>{_CSS}</style></head><body>")

    # Header
    targets_str = h(", ".join(workspace.targets)) if workspace.targets else "N/A"
    lines.append(f"<h1>⬡ SpectreNet Pentest Report</h1>")
    lines.append(f"<div class='meta'>")
    lines.append(f"  <span><strong>Operator:</strong> {h(operator)}</span>")
    lines.append(f"  <span><strong>Generated:</strong> {h(now)}</span>")
    lines.append(f"  <span><strong>Targets:</strong> {targets_str}</span>")
    lines.append(f"</div>")

    # Network findings
    if hosts:
        lines.append("<h2>Network Findings</h2>")
        for ip, ports in sorted(hosts.items()):
            lines.append(f"<h3><code>{h(ip)}</code></h3>")
            lines.append("<table><thead><tr><th>Port</th><th>Proto</th><th>Service</th><th>Version</th></tr></thead><tbody>")
            for p in sorted(ports, key=lambda x: int(x.get("port", 0) or 0)):
                lines.append(
                    f"<tr><td>{h(p.get('port',''))}</td>"
                    f"<td>{h(p.get('proto','tcp'))}</td>"
                    f"<td>{h(p.get('service',''))}</td>"
                    f"<td>{h(p.get('version',''))}</td></tr>"
                )
            lines.append("</tbody></table>")

    # Loot
    all_loot = loot.all()
    if all_loot:
        lines.append("<h2>Loot &amp; Credentials</h2>")
        _badge_map = {"cred": "badge-red", "hash": "badge-yellow", "file": "badge-cyan", "secret": "badge-yellow"}
        for loot_type in LootVault.TYPES:
            entries = loot.by_type(loot_type)
            if not entries:
                continue
            lines.append(f"<h3>{h(loot_type.capitalize())}s</h3><ul>")
            for entry in entries:
                cls = _badge_map.get(loot_type, "badge-cyan")
                ts  = entry["t"][:16]
                lines.append(
                    f"<li><span class='badge {cls}'>{h(loot_type)}</span>"
                    f"<code>{h(entry['text'])}</code>"
                    f"  <span style='color:var(--grey);font-size:11px'>{h(ts)}</span></li>"
                )
            lines.append("</ul>")

    # Notes
    if workspace.notes:
        lines.append("<h2>Notes</h2><ul>")
        for n in workspace.notes:
            ts = n["t"][:16]
            lines.append(f"<li class='note-item'>{h(n['text'])}  <em>{h(ts)}</em></li>")
        lines.append("</ul>")

    # Findings
    if workspace.findings:
        lines.append("<h2>Findings</h2><ul>")
        for f in workspace.findings:
            lines.append(f"<li>{h(str(f))}</li>")
        lines.append("</ul>")

    # Command timeline
    if workspace.commands:
        lines.append("<h2>Command Timeline</h2><pre>")
        for c in workspace.commands:
            ts = c["t"][:16]
            lines.append(f"[{h(ts)}] {h(c['cmd'])}")
        lines.append("</pre>")

    lines.append("<footer>Generated by SpectreNet — Always one step ahead</footer>")
    lines.append("</body></html>")

    return "\n".join(lines)
