"""Generate a Markdown pentest report from workspace + loot + findings."""
from __future__ import annotations

from datetime import datetime
from spectrenet.workspace import Workspace
from spectrenet.loot import LootVault


def generate_report(
    workspace: Workspace,
    loot: LootVault,
    hosts: dict,
    operator: str = "operator",
) -> str:
    now   = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []

    lines += [
        "# SpectreNet Pentest Report",
        "",
        f"**Operator:** {operator}  ",
        f"**Generated:** {now}  ",
        f"**Targets:** {', '.join(workspace.targets) if workspace.targets else 'N/A'}",
        "",
        "---",
        "",
    ]

    # ── Scope / Targets ───────────────────────────────────────────────────
    if workspace.targets:
        lines += ["## Targets", ""]
        for t in workspace.targets:
            lines.append(f"- `{t}`")
        lines.append("")

    # ── Findings (from Findings Panel) ───────────────────────────────────
    if hosts:
        lines += ["## Network Findings", ""]
        for ip, ports in sorted(hosts.items()):
            lines.append(f"### {ip}")
            lines.append("")
            lines.append("| Port | Proto | Service | Version |")
            lines.append("|------|-------|---------|---------|")
            for p in sorted(ports, key=lambda x: int(x.get("port", 0) or 0)):
                port    = p.get("port",    "")
                proto   = p.get("proto",   "tcp")
                service = p.get("service", "")
                version = p.get("version", "")
                lines.append(f"| {port} | {proto} | {service} | {version} |")
            lines.append("")

    # ── Loot / Credentials ───────────────────────────────────────────────
    all_loot = loot.all()
    if all_loot:
        lines += ["## Loot & Credentials", ""]
        for loot_type in LootVault.TYPES:
            entries = loot.by_type(loot_type)
            if not entries:
                continue
            lines.append(f"### {loot_type.capitalize()}s")
            lines.append("")
            for e in entries:
                ts = e["t"][:16]
                lines.append(f"- `{e['text']}`  _{ts}_")
            lines.append("")

    # ── Notes ─────────────────────────────────────────────────────────────
    if workspace.notes:
        lines += ["## Notes", ""]
        for n in workspace.notes:
            ts = n["t"][:16]
            lines.append(f"- {n['text']}  _{ts}_")
        lines.append("")

    # ── Findings from workspace ───────────────────────────────────────────
    if workspace.findings:
        lines += ["## Findings (Workspace)", ""]
        for f in workspace.findings:
            lines.append(f"- {f}")
        lines.append("")

    # ── Command Timeline ──────────────────────────────────────────────────
    if workspace.commands:
        lines += ["## Command Timeline", "", "```"]
        for c in workspace.commands:
            ts = c["t"][:16]
            lines.append(f"[{ts}] {c['cmd']}")
        lines += ["```", ""]

    lines += [
        "---",
        "",
        "_Generated by SpectreNet — Always one step ahead_",
    ]

    return "\n".join(lines)
